/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#141f07',
        'surface-container-highest': '#e3e3de',
        'on-error-container': '#93000a',
        'background': '#faf9f5',
        'surface-bright': '#faf9f5',
        'tertiary-container': '#c9bce1',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f1f1ed',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'secondary': '#7c5357',
        'on-tertiary-container': '#544a69',
        'tertiary-fixed': '#eaddff',
        'on-tertiary-fixed': '#1f1732',
        'surface-tint': '#556345',
        'primary-fixed-dim': '#bdcca8',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1a1c1a',
        'on-secondary-fixed-variant': '#623c40',
        'surface-dim': '#dadad6',
        'on-primary-container': '#465337',
        'on-secondary-container': '#795154',
        'secondary-fixed': '#ffdadc',
        'on-surface-variant': '#45483f',
        'tertiary-fixed-dim': '#cdc1e5',
        'on-secondary-fixed': '#301216',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#4b4260',
        'primary': '#556345',
        'surface-container-low': '#f4f4ef',
        'surface-variant': '#e3e3de',
        'on-surface': '#1a1c1a',
        'inverse-primary': '#bdcca8',
        'outline-variant': '#c5c8bc',
        'surface-container': '#efeeea',
        'primary-fixed': '#d9e8c2',
        'surface-container-high': '#e9e8e4',
        'surface': '#faf9f5',
        'tertiary': '#635979',
        'secondary-container': '#fdc7cb',
        'outline': '#75786e',
        'inverse-surface': '#2f312e',
        'on-primary-fixed-variant': '#3e4b2f',
        'primary-container': '#b8c7a3',
        'secondary-fixed-dim': '#eeb9bd',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '1rem',
        'stack-md': '2rem',
        'inner-padding': '2rem',
        'section-gap': '80px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-md': ['DM Sans', 'sans-serif'],
        'label-caps': ['Montserrat', 'sans-serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'quote-italic': ['Playfair Display', 'serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        'script': ['Dancing Script', 'cursive'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.5', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'quote-italic': ['24px', { lineHeight: '1.4', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
